# fly.toml app configuration file generated for signatures-backend on 2025-02-25T23:15:24Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "signatures-backend"
primary_region = "arn"

[build]
  dockerfile = "Dockerfile"

[env]
  PORT = "8080"
  NODE_ENV = "production"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]

  [[http_service.ports]]
    handlers = ["http"]
    port = 80

  [[http_service.ports]]
    handlers = ["tls", "http"]
    port = 443
